# Generated by Django 5.1.2 on 2024-12-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_followers_customuser_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='following',
            new_name='followers',
        ),
    ]
